
name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -c --skip-tests
              env:
                  NS_BASE_URL: ${{ secrets.BASEURL }}
                  NS_TOKEN_SECRET: ${{ secrets.TOKENSECRET }}
                  NS_TOKEN: ${{ secrets.TOKEN }}
                  NS_CLIENT_ID: ${{ secrets.CONSUMERID }}
                  NS_CLIENT_SECRET: ${{ secrets.CONSUMERSECRET }}
                  NS_ACCOUNTID: ${{secrets.ACCOUNTID}}
                  
            - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
              with:
                   timeout: 1h
                   port: 4000
                   ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
                  
